[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
delegation_program = "JAzubT5NSiyRkLgaFRTkrdLGzzMb57CVhMhdDCiqoRu6"

[programs.testnet]
delegation_program = "JAzubT5NSiyRkLgaFRTkrdLGzzMb57CVhMhdDCiqoRu6"

[programs.mainnet]
xenblocks_airdrop_tracker = "JAzubT5NSiyRkLgaFRTkrdLGzzMb57CVhMhdDCiqoRu6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.mainnet.x1.xyz"
wallet = "~/.config/solana/id.json"

[scripts]
deploy = "anchor deploy"
deploy-localnet = "anchor deploy --provider.cluster http://localhost:8899 --program-id target/deploy/delegation_program-keypair-localnet.json"
deploy-testnet = "anchor deploy --provider.cluster https://rpc.testnet.x1.xyz --program-id target/deploy/delegation_program-keypair-testnet.json"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
